export const UPDATE_STEP = 'UPDATE_STEP';
export const UPDATE_MOBILE = 'UPDATE_MOBILE';
export const UPDATE_PERSONAL_DETAILS = 'UPDATE_PERSONAL_DETAILS';
export const UPDATE_DOCUMENTS = 'UPDATE_DOCUMENTS';
export const UPDATE_BANK_DETAILS = 'UPDATE_BANK_DETAILS';
export const ACCEPT_TERMS = 'ACCEPT_TERMS';
export const RESET_FORM = 'RESET_FORM';
